version: '3.6'

services:
  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  tylerrwallcom:
    extends:
      file: ../sites/tylerrwall.com/docker-compose.yml
      service: tylerrwallcom
    restart: always
    environment:
      - VIRTUAL_HOST=tylerrwall.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=tylerrwall.com
      - LETSENCRYPT_EMAIL=tyler.r.wall@gmail.com

  anticsolutionscom:
    extends:
      file: ../sites/anticsolutions.com/docker-compose.yml
      service: anticsolutionscom
    restart: always
    environment:
      - VIRTUAL_HOST=anticsolutions.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=anticsolutions.com
      - LETSENCRYPT_EMAIL=tyler.r.wall@gmail.com

networks:
  default:
    name: nginx-proxy
