version: '3.6'

services:
  anticsolutionscom:
    image: nginx
    restart: always
    volumes:
      - "./:/usr/share/nginx/html"
    environment:
      # NGINX-PROXY ENVIRONMENT VARIABLES
      - VIRTUAL_HOST=anticsolutions.com 
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=anticsolutions.com 
      - LETSENCRYPT_EMAIL=tyler.r.wall@gmail.com
      # /END NGINX-PROXY ENVIRONMENT VARIABLES
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
